version: '3.10'

services:
  xclip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xclip
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app:/app
    working_dir: /app
    command: ["python3", "main.py"]
    stdin_open: true     # <- 인터랙티브 입력 허용
    tty: true             # <- 가상 터미널 할당
