version: '3.10'

services:
  xclip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xclip
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]
